name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd messaging_app
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        cd messaging_app
        python manage.py migrate --noinput
      env:
        DATABASE_URL: mysql://test_user:test_password@localhost:3306/test_db
        DJANGO_SETTINGS_MODULE: messaging.settings

    - name: Run tests
      run: |
        cd messaging_app
        python manage.py test --noinput --verbosity=2
      env:
        DATABASE_URL: mysql://test_user:test_password@localhost:3306/test_db
        DJANGO_SETTINGS_MODULE: messaging.settings